# Jekyll configuration file

# Site settings
# theme: jekyll-sleek
title: Curtin Robotics Club
acronym: CRoC
email: curtinroboticsclub@gmail.com
description: >
  Curtin Robotics Club is a student guild club run by and for students. We build
  robots and participate in robotics competitions, teach high school students to
  build a robot and much more.
url: "http://curtinrobotics.github.io" # the base hostname & protocol for your site
github_username: curtinrobotics
github_repository: curtinrobotics.github.io


# Build settings
markdown: kramdown

# Don't include readme and license files
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
